version: 2

before:
  hooks:
    - go mod tidy

builds:
  - id: default
    env:
      - CGO_ENABLED=0
    main: ./cmd/kcl/main.go
    binary: kcl
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - "-X kcl-lang.io/cli/pkg/version.version={{ .Version }}"

archives:
  - id: default
    ids:
      - default
    name_template: "kcl-v{{ .Version }}-{{ .Os }}-{{ .Arch }}"
    format_overrides:
      - goos: windows
        formats:
          - zip

homebrew_casks:
  - name: kcl
    ids:
      - default
    binaries:
      - kcl
    repository:
      owner: kcl-lang
      name: homebrew-tap
      branch: main
    directory: Casks
    homepage: "https://github.com/kcl-lang/kcl"
    description: "KCL Command Line Interface"
    license: "Apache-2.0"
    commit_author:
      name: GoReleaser Bot
      email: goreleaser@carlosbecker.com
    url:
      verified: github.com/kcl-lang/cli

scoops:
  - name: kcl
    url_template: "https://github.com/kcl-lang/cli/releases/download/{{ .Tag }}/kcl-v{{ .Version }}-{{ .Os }}-{{ .Arch }}.zip"
    repository:
      owner: kcl-lang
      name: scoop-bucket
      branch: main
      token: "{{ .Env.GITHUB_TOKEN }}"
    directory: Scoops
    commit_author:
      name: goreleaserbot
      email: bot@goreleaser.com
    commit_msg_template: "Scoop update for kcl version {{ .Tag }}"
    homepage: "https://github.com/kcl-lang/kcl"
    description: "KCL Command Line Interface"
    license: "Apache-2.0"